String.toLocaleString({
  "en-us": {
    "title":"Simulation of Linear Array of Point Sources",
    "header2":"Sound pressure level simulation",
    "header4":"of a linear array of point sources",
    "intensity_map":"SPL Map >",
    "directivity_pattern":"Directivity Pattern >",
    "dirPatternLabel":"Directivity Pattern:",
    "countLabel":"Element Count:",
    "elemRadiusLabel":"Element Size, m:",
    "elemDistance":"Elements Separation, m:",
    "frequencyLabel":"Frequency, Hz:",
    "speedLabel":"Speed of Sound, m/s:",
    "brightnessLabel":"Magnitude scale:",
    "scaleLabel":"Plot Scale:",
    "waterbtn":"Water",
    "airbtn":"Air",
    "helpfeedback":"Help & Feedback",
    "Frequency: ":"Frequency: ",
    " Hz  |  Elements Q-ty: ":" Hz  |  Elements Q-ty: ",
    "  |  Spacing: ":"  |  Spacing: "
  },

  "ru-ru": {
    "title":"Моделирование линейной решетки точечных акустических излучателей",
    "header2":"Карта звукового поля",
    "header4":"массива точечных акустических излучателей",
    "intensity_map":"Карта звукового давления >",
    "directivity_pattern":"Характеристика направленности >",
    "dirPatternLabel":"ХН одного элемента:",
    "countLabel":"Кол-во элементов:",
    "elemRadiusLabel":"Линейный размер элемента, м:",
    "elemDistance":"Расстояние между элементами, м:",
    "frequencyLabel":"Частота, Гц:",
    "speedLabel":"Скорость распространения, м/с:",
    "brightnessLabel":"Уровень сигнала:",
    "scaleLabel":"Масштаб:",
    "waterbtn":"Вода",
    "airbtn":"Воздух",
    "helpfeedback":"Обратная связь",
    "Frequency: ":"Частота: ",
    " Hz  |  Elements Q-ty: ":" Гц  | Кол-во: ",
    "  |  Spacing: ":"  |  Шаг: "
  },

  "uk-ua": {
    "title":"Моделювання линійної решітки точкових акустичних елементів",
    "header2":"Мапа звукового поля",
    "header4":"массиву точкових акустичних випромінювачів",
    "intensity_map":"Мапа звукового тиску >",
    "directivity_pattern":"Характеристика спрямованості >",
    "dirPatternLabel":"Характеристика спрямованості:",
    "countLabel":"Кол-во випромінювачів:",
    "elemRadiusLabel":"Линійний розмір елемента, м:",
    "elemDistance":"Відстань між елементами, м:",
    "frequencyLabel":"Частота, Гц:",
    "speedLabel":"Швидкість розповсюдження, м/с:",
    "brightnessLabel":"Рівень сигналу:",
    "scaleLabel":"Масштаб:",
    "waterbtn":"Вода",
    "airbtn":"Повітря",
    "helpfeedback":"Відгуки та допомога",
    "Frequency: ":"Частота: ",
    " Hz  |  Elements Q-ty: ":" Гц  |  Кількість: ",
    "  |  Spacing: ":"  |  Крок: "
  }
});
